### ISSUE TITLE
ModuleNotFoundError: No module named 'lib.helpers.decorator_helper_level' 

### ISSUE THREAD

**Issue by rockywind** [amazon-research/progressive-coordinate-transforms#7]
When I run `python ../../tools/train_val.py --config config_val.yaml`,
I get the error as follow.
> Traceback (most recent call last):
  File "../../tools/train_val.py", line 19, in <module>
    from lib.helpers.trainer_helper import Trainer
  File "/newnfs/zzwu/08_3d_code/progressive-coordinate-transforms/lib/helpers/trainer_helper.py", line 11, in <module>
    from lib.helpers.decorator_helper_level import decorator_level
ModuleNotFoundError: No module named 'lib.helpers.decorator_helper_level'

**Comment by Willy0919** [comment]
Sorry for the bugs, you can delete the related row (line 11 and 26). Or update the trainer_helper.py from our git.

**Comment by rockywind** [comment]
But the self.val_decorator is call in the following code.
` loss, stat_dict = self.val_decorator(self.model, batch_data, self.cfg['decorator'])`

**Comment by Willy0919** [comment]
We do not call the function eval_one_epoch_1(), this function is my debug code.
